### ISSUE TITLE
About Null Exception

### ISSUE THREAD

**Issue by zdx199861** [Li-Zhaoxi/AAMED#13]
![image](https://user-images.githubusercontent.com/100758299/156322194-fefa8aa6-ff71-4a9e-9bb9-6bf5de47dcba.png)
![image](https://user-images.githubusercontent.com/100758299/156322264-e9ea1217-c2e8-411b-83ed-7e469a20b994.png)
the function "getlinkArcs‘’ in FLED.cpp causes exception all the time , why this happend?

**Comment by Li-Zhaoxi** [comment]
@zdx199861 This bug seems to appear in VS2017 or higher version.

you can replace `GroupPart<linkArc> lA;` with `std::vector<linkArc> lA`. 

Some codes associated with ' lA' also need to be modified.

like,

`lA[i]->idx_linking.push_back(j)' -> 'lA[i].idx_linking.push_back(j)`
`lA[i]->idx_notlink.push_back(j)' -> 'lA[i].idx_notlink.push_back(j)`
`lA[i]->idx_linked.push_back(j)' -> 'lA[i].idx_linked.push_back(j)`

**Comment by zdx199861** [comment]
thank you!!!!!!!!!! It works well!
